---
title: "Census Demo"
author: "Yiyang Shi"
date: "4/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidycensus)
library(tidyverse)
library(sf)
options(tigris_use_cache = TRUE)
census_api_key("593dedcd53f3a58724af5ac88fc2916d21a6ed05")
```

```{r}
v20 <- load_variables(2020, "acs5", cache = TRUE)
```

```{r}
VARS <- c(Income = "B19013_001", Pop = 'B01003_001', Age = "B01002_001")


DC_quant <- get_acs(state = "DC", 
                    geography = "tract", 
                    variables = VARS, 
                    year = 2020,
                    geometry = TRUE, 
                    output='wide')

```
```{r}
get_DC_data <- function(V,V1,NAMES){
  DC_cat <- get_acs(state = "DC", geography = "tract", 
                        variables = V, geometry = TRUE, output='wide', summary_var = V1)
 
  DC_cat %>% 
    select(-ends_with('M')) %>%
    mutate(Total = select(.,-c(GEOID,NAME,summary_est,summary_moe)) %>% rowSums(na.rm=TRUE)) %>%
    mutate(across(-c(GEOID,NAME,summary_est,summary_moe), ~.x/DC_cat$summary_est)) %>%
    select(-c(summary_est,summary_moe,Total))
}
```

```{r}
V1 <- "B02001_001"
V <- paste0("B02001_0",str_pad(c(2:8),2,"0",side='left'))
NAMES <- v20 %>% filter(name %in% V) %>% pull(label) %>% str_replace('Estimate\\!\\!Total\\:\\!\\!','')
race = get_DC_data(V,V1,NAMES) # error message pop up here
names(race) = c('GEOID','NAME',trimws(paste0('Race_',str_sub(NAMES,0,26))))
NMS <- c(NMS,V)

# Error: Problem with `mutate()` column `Total`. i `Total = select(., -c(GEOID, NAME, summary_est, summary_moe)) %>% rowSums(na.rm = TRUE)`. x 'x' must be numeric
```

