---
title: "final_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("mergedData.RData")
load("spatialData.RData")
```

```{r}
library(geeM)
library(dplyr)
library(ggplot2)
library(sf)
```

```{r}
colnames(data)
data <- data %>% na.omit()
```

```{r}
model_1 <- geem(rider_number ~ avg_duration + avg_dist + TemperatureCat +  HumidityCat+ WindCat + IncomeE + AgeE + distToWM + `Race_White alone`, id = start_station_id, data = data, corstr = "independence")
```

```{r}
model_2 <- geem(rider_number ~ avg_duration + avg_dist + TemperatureCat +  HumidityCat+ WindCat + IncomeE + AgeE + distToWM + `Race_White alone`, id = start_station_id, data = data, corstr = "exchangeable")
```

```{r}
model_3 <- geem(rider_number ~ avg_duration + avg_dist + TemperatureCat +  HumidityCat+ WindCat + IncomeE + AgeE + distToWM + `Race_White alone`, id = start_station_id, data = data, corstr = "ar1")
```


```{r}
summary(model_1)
summary(model_2)
summary(model_3)
```

```{r}
# data <- data %>% 
#   select(c(start_date,  TemperatureCat, HumidityCat, WindCat, `Race_White alone`, rider_number, start_station_id, GEOID, distToWM)) 
#   # na.omit()

super_simple_mod <- geem(rider_number ~ TemperatureCat + HumidityCat + WindCat + `Race_White alone`+distToWM,
                         data = data, 
                         id = start_station_id, 
                         corstr = "exchangeable")


```



```{r}
data$GEE_resid = data$rider_number - predict(super_simple_mod)


DC_resid_avg <- data %>% 
  group_by(GEOID) %>% 
  summarize(resid_by_census = mean(GEE_resid)) %>% 
  right_join(DC_data, by = "GEOID") 

data %>% 
  filter(start_date == "2021-07-04") %>% 
  ggplot() + 
  geom_sf(data=DC_data, fill = "white")+
  geom_sf(aes(geometry=geometry, color = GEE_resid),size=.5) +
  theme_classic() + 
  labs(title = "Model Prediction Errors from each station on July 4th, 2021", color = "Prediction Errors") +
 # scale_color_viridis_c('Total number of rides',option = "magma") +
  scale_color_gradient2(low = "blue",mid='white', high = "red") 

IDS <- data %>% filter(abs(scale(GEE_resid))>3) %>% count(start_station_id) %>% arrange(desc(n)) %>% slice(1:5) %>% pull(start_station_id)
  

data %>% 
  filter(start_station_id %in% IDS) %>% 
  ggplot(aes(x = start_date, y = GEE_resid, color=factor(start_station_id))) + 
  geom_smooth()

data %>% 
  filter(start_station_id %in% IDS) %>% 
  filter(start_date == "2021-07-04") %>% 
  ggplot() + 
  geom_sf(data=DC_data, fill = "white")+
  geom_sf(aes(geometry=geometry, color = GEE_resid),size=.5) +
  theme_classic() + 
  labs(title = "Model Prediction Errors from each station on July 4th, 2021", color = "Prediction Errors") +
  scale_color_gradient2(low = "blue",mid='white', high = "red") 


DC_resid_avg %>% 
  ggplot() +
  geom_sf(aes(fill = resid_by_census,
              geometry = geometry)) +
  scale_fill_gradient2(name = "Residuals", mid = "white", high = "red", low = "blue") + 
  labs(title = "GEE Residuals Map") +
  theme_classic() + 
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) 
```

```{r}
summary(super_simple_mod)
```

```{r}
data %>% filter(GEOID == "11001004100")
```

