```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE)
library(dplyr)
library(lubridate)
library(stringr)
library(ggplot2)
library(sf)
library(spdep)
library(splines)
library(scales)
library(spatialreg)
library(gridExtra)
library(xtable)
library(DT)
library(readr)
set.seed(452)

load('SpatialData.RData')
```

```{r}
bike_coord <- bike %>% 
  group_by(start_station_id) %>%
  summarize(start_lat = mean(start_lat,na.rm=TRUE), start_lng = mean(start_lng,na.rm=TRUE))

bike_coord %>% arrange(start_station_id)

bike_coord <- bike_coord %>% st_as_sf(coords=c('start_lng','start_lat'))

#bike_sf <- inner_join(clean_bike, bike_coord, by = "start_station_id")
```


```{r}
ggplot(DC_data) + 
  geom_sf(fill='white') + 
  geom_sf(data = areawater,fill='blue')  + 
  geom_sf(data = bike_coord_sub,size=.2,color='red') + 
  geom_sf(data = roads_sub,color='orange') + 
  theme_void()
```

```{r}
ggplot(DC_data) + 
  geom_sf(aes(fill = AgeE),size=.1) +
  geom_sf(data = bike_spatial,color='yellow',size=.2) + 
  geom_sf(data = areawater,fill='lightblue',color='lightblue') + 
  geom_sf(data = roads_sub,color='orange') +
  geom_sf(data = points_of_interest, aes(geometry=geometry), color = 'red') +
  scale_fill_continuous(name = "Median Age", labels = comma, high = "blue", low = "lightgrey") +
  labs(title = "Median Age by Census Tract") +
  theme_classic() + 
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank()) 
```

```{r}
# Census tract you might consider to categorized. Since they dont have a income median, but they do have stations in the area that potentially have plenty of daily riders.

# Census tract 9800 includes the white house, capital, Lincoln memorial and the monument. 
# Census Tract 2.01 is Georgetown University
# Census tract 68.04 is the includes Kennedy memorial stadium
# Census tract 95.11 is the Catholic University of America
bike_spatial %>% 
  filter(is.na(IncomeE)) %>% 
  count(NAME)
```


